### PR TITLE
Added data logging in excel

### PR DESCRIPTION
**Pull request by yasamanibrahimova**

### CODE REVIEW

**Review by aTurukDCCA — APPROVED** [review]

**Comment by farruhOsman** [comment]
@yasamanibrahimova  can you fix the conflict? also attach screenshot of test runs? and extent report?

**Comment by yasamanibrahimova** [comment]
> @yasamanibrahimova can you fix the conflict? also attach screenshot of test runs? and extent report?

I see that the conflict occurred because PR #21 by Rashad was merged a few minutes ago. I will resolve the conflict, take a look at everything, and add the requested screenshot and extent report as well.

Thank you!

**Review by aTurukDCCA — APPROVED** [review]

**Comment by yasamanibrahimova** [comment]
image
image

**Comment by yasamanibrahimova** [comment]
image

**Review by farruhOsman — APPROVED** [review]

**Comment by yasamanibrahimova** [comment]
Failure case:
image

**Comment by yasamanibrahimova** [comment]
image

**Pull request merged**
